apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-lab17
  labels:
    app: frontend-lab17
spec:
  selector:
    matchLabels:
      app: frontend-lab17
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend-lab17
    spec:
      containers:
        - name: frontend-lab17
          image: jsj1040/frontend-lab17
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
