apiVersion: v1
kind: Service
metadata:
  name: frontend-lab17
  labels:
    name: frontend-lab17
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: frontend-lab17
  type: NodePort
